### ISSUE TITLE
Nothing is uploadet

### ISSUE THREAD

**Issue by NinjaOne** [bsdz/google-drive-remarkable-sync#24]
For about a week, nothing has uploadet when running the script.

Google Apps Scripts log show no errors, and everything looks as expected. But nothing shows up on the tablet.

**Comment by ablwr** [comment]
I am also experiencing this, as of a few days ago.

I think this may be related to this rmapi issue (https://github.com/juruen/rmapi/issues/187), caused by reMarkable changing their cloud API and breaking functionality downstream in exactly this way: silent failure to add files. Do you think this is impacting google-drive-remarkable-sync too?

The funny thing is that the google drive sync does successfully upload to the cloud, because I'm able to see the changes on the reMarkable iPhone app. They just never make it to the device itself. 
 
By the way, this has been such a great way for me to keep my ebooks organized in my reMarkable, thank you for making it!

**Comment by bsdz** [comment]
Sorry for not responding sooner. It is quite possible there's an issue. Is haven't used my remarkable for a little while so can't confirm. Curiously I see there's a new integrations feature on their website. It might be a better replacement for my old script https://my.remarkable.com/integrations

**Comment by NinjaOne** [comment]
Yeah. Looks like official support for Google Drive is comming.
Thanks for making this, though. Made a difference for me at least. 🙂

**Comment by bsdz** [comment]
Thank you. It's worked well for some time. Incidentally I did create a sample pdf in my Google drive and it did flow to my remarkable. So perhaps this script is still working for now.

**Comment by ablwr** [comment]
What I gathered from the rmapi breaking changes is they're rolling it out gradually (without notifying users), so it's like a slow-motion mass breaking of dependencies, which has made identification and bug-squashing more difficult. I guess @NinjaOne was one of the unlucky, and I quickly followed.

I opted into the reMarkable beta user updates though, and was able to get their native Google Drive integration. It's pretty slick, although folks that want a bulk download-and-sync may not find it as useful. 

Again thanks for making this original integration, which was a very nice workflow for me!
