### ISSUE TITLE
Syncs folder inside a folder

### ISSUE THREAD

**Issue by hmenzagh** [bsdz/google-drive-remarkable-sync#6]
When I sync to a Folder on my RM, I get `/Google Drive/Books/*.pdf` instead of `/Google Drive/*.pdf` since this library is mostly centered around a single folder sync it would be nice to have the option of uploading the files directly in the parent directory ! Is there a way of doing that ?

**Comment by bsdz** [comment]
I vaguely recall being able to set gdFolderSearchParams to a string that returned Drive's root folder. I can't recall what that was. Perhaps try the empty string or ["root"](https://stackoverflow.com/questions/33907267/google-drive-root-folder-id). Alternatively, you could take a look at the expression syntax at https://developers.google.com/drive/api/v3/search-files. I hope that helps.

**Comment by hmenzagh** [comment]
I dit try that, and `root` works, but it creates a folder called `My Drive` instead .. x)

**Comment by oyvindlr** [comment]
I don't think the solution to this issue is to allow to save to remarkable's root folder, but rather that the _contents_ of the gDrive folder is synced to the selected remarkable folder instead of the folder itself. The way this works now, you will always end up with an unnecessary folder whose only contents is another folder. But maybe that is harder to implement.

Edit: Not that hard to implement, I added a new pull request #22
